-- ==============================================================================
-- Smart Expense Tracker — PostgreSQL DDL
--
-- This DDL mirrors the backend JPA entities 1:1
-- (package com.expensetracker.model, ddl-auto=update). Table/column names use
-- Hibernate's physical naming (camelCase -> snake_case), all primary keys are
-- BIGINT identity columns, enums are stored as VARCHAR.
--
-- The backend will also auto-update the schema at startup
-- (spring.jpa.hibernate.ddl-auto=update), so this file mainly matters for
-- fresh installs (docker-compose postgres init) and for documentation.
-- ==============================================================================

-- ----------------------------------------------------------------------------
-- users
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255),
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,   -- BCrypt hash, never plain text
    created_at    TIMESTAMPTZ NOT NULL
);

-- ----------------------------------------------------------------------------
-- expenses
-- ----------------------------------------------------------------------------
CREATE TABLE expenses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    amount        NUMERIC(12,2) NOT NULL,
    category      VARCHAR(255) NOT NULL,   -- Category enum name, e.g. 'Food'
    date          DATE NOT NULL,
    payment_mode  VARCHAR(255),            -- e.g. UPI, Cash, Card, NetBanking
    merchant      VARCHAR(255),
    notes         VARCHAR(1000),
    source        VARCHAR(255) NOT NULL,   -- MANUAL | QR | BANK | RECURRING
    bank_txn_ref  VARCHAR(255),            -- provider txn id, drives dedup
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ
);

CREATE INDEX idx_expenses_user_date ON expenses (user_id, date);

-- ----------------------------------------------------------------------------
-- budgets: one monthly limit per (user, category)
-- ----------------------------------------------------------------------------
CREATE TABLE budgets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category        VARCHAR(255) NOT NULL, -- Category enum name
    monthly_limit   NUMERIC(12,2) NOT NULL,
    alert_threshold DOUBLE PRECISION NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_budget_user_category UNIQUE (user_id, category)
);

-- ----------------------------------------------------------------------------
-- recurring_expenses: rules materialized into expenses by a scheduled job
-- ----------------------------------------------------------------------------
CREATE TABLE recurring_expenses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,   -- e.g. "Netflix", "House rent"
    amount        NUMERIC(12,2) NOT NULL,
    category      VARCHAR(255) NOT NULL,   -- Category enum name
    frequency     VARCHAR(255) NOT NULL,   -- MONTHLY | WEEKLY
    next_due_date DATE NOT NULL,
    payment_mode  VARCHAR(255),
    merchant      VARCHAR(255),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_recurring_due ON recurring_expenses (active, next_due_date);

-- ----------------------------------------------------------------------------
-- bank_consents: a user's consent for a bank data source (mock or real AA)
-- ----------------------------------------------------------------------------
CREATE TABLE bank_consents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    bank_name   VARCHAR(255) NOT NULL,
    consent_id  VARCHAR(255) NOT NULL UNIQUE, -- provider-side consent reference
    status      VARCHAR(255) NOT NULL,        -- PENDING | APPROVED | REVOKED | EXPIRED
    created_at  TIMESTAMPTZ NOT NULL
);

-- ----------------------------------------------------------------------------
-- bank_accounts: accounts under a consent.
-- SECURITY: only MASKED account numbers are stored. Never credentials/PINs.
-- ----------------------------------------------------------------------------
CREATE TABLE bank_accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    consent_id          BIGINT REFERENCES bank_consents (id) ON DELETE CASCADE,
    bank_name           VARCHAR(255) NOT NULL,
    masked_number       VARCHAR(255) NOT NULL, -- e.g. 'XXXX-XXXX-1234'
    external_account_id VARCHAR(255),          -- provider-side id, opaque
    created_at          TIMESTAMPTZ NOT NULL
);

-- ----------------------------------------------------------------------------
-- bank_transactions: raw provider transactions before they become expenses.
-- (user_id, txn_id) is unique and drives dedup on import.
-- ----------------------------------------------------------------------------
CREATE TABLE bank_transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    txn_id      VARCHAR(255) NOT NULL,   -- provider's txn reference
    date        DATE NOT NULL,
    amount      NUMERIC(12,2) NOT NULL,
    type        VARCHAR(255) NOT NULL,   -- DEBIT | CREDIT (only debits -> expenses)
    merchant    VARCHAR(255),
    vpa         VARCHAR(255),            -- UPI id, e.g. "shop@okhdfcbank"
    note        VARCHAR(255),
    balance     NUMERIC(12,2),           -- balance after txn (informational)
    processed   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_banktxn_user_txn UNIQUE (user_id, txn_id)
);

CREATE INDEX idx_bank_txn_user_date ON bank_transactions (user_id, date);

-- ----------------------------------------------------------------------------
-- merchant_mappings: per-user merchant -> category learning from corrections.
-- Checked before the ML model during categorization; hit_count grows with
-- each correction for the same merchant.
-- ----------------------------------------------------------------------------
CREATE TABLE merchant_mappings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    merchant_key VARCHAR(255) NOT NULL,   -- normalized: lowercased, trimmed
    category     VARCHAR(255) NOT NULL,   -- Category enum name
    hit_count    INTEGER NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ,
    CONSTRAINT uq_merchant_user_key UNIQUE (user_id, merchant_key)
);

CREATE INDEX idx_merchant_map_lookup ON merchant_mappings (user_id, merchant_key);

-- ----------------------------------------------------------------------------
-- sync_runs: audit log of bank sync executions
-- ----------------------------------------------------------------------------
CREATE TABLE sync_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status            VARCHAR(255) NOT NULL, -- SUCCESS | PARTIAL | FAILED
    new_transactions  INTEGER NOT NULL,
    duplicates_skipped INTEGER NOT NULL,
    message           VARCHAR(255),
    started_at        TIMESTAMPTZ NOT NULL,
    finished_at       TIMESTAMPTZ
);
